### ISSUE TITLE
Change Mining Collection Time

### ISSUE THREAD

**Issue by majestic44** [Omega-Corp-myDU/featurerequest#2]
Change mining collection time from **1 hour** to **30 min**

**Comment by Nickle-Eye** [comment]
### Jaseac suggested this

``` yaml
parent: IndustryInfrastructure

calibrationDecreaseRatePerHour: making it 0 will mean it doesn't have to be calibrated again. You can if you want to, but you don't have to.

runtimeHours: changes how long till it deposits into container currently 1 hour

miningEfficiency: could probably change that to 10, to match the units
```

### I would like to see the following

``` yaml
parent: IndustryInfrastructure

calibrationDecreaseRatePerHour: 720 so have to calibrate every 30days
runtimeHours: .5 so 30min
miningEfficiency: 10
```

### APPROVED
