### ISSUE TITLE
Add legacy planets

### ISSUE THREAD

**Issue by Nickle-Eye** [Omega-Corp-myDU/featurerequest#5]
### Come up with a list of planets to add back in

``` yaml
Ion
Lacobus
Symeon
Jago
Teoma
Feil
Maybe Alioth
```

### Make another safe zone

``` yaml
- centerX: -4381016.8968
    centerY: -50452606.9770
    centerZ: 563748.2122
    radius: 25000000
```

### Name the New Planets

``` yaml
Ion = Nova
Lacobus = Pandora
Symeon = Nebula
Jago = Elysium
Teoma = Zomecia
Feil = Terra Nova
Alioth = Titan 
```

### Docker Commands

``` yaml
Linux Command
docker compose run -v $PWD:/input --entrypoint bash sandbox

Windows Command
docker-compose run -v "%cd%:/input" --entrypoint bash sandbox


```
